/*
 * Copyright (c) 2025. Xodium.
 * All rights reserved.
 */

// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $carousel from "./islands/carousel.tsx";
import * as $dashboard_1 from "./islands/dashboard.tsx";
import * as $logout from "./islands/logout.tsx";
import * as $sidebar from "./islands/sidebar.tsx";
import * as $teamcards from "./islands/teamcards.tsx";
import * as $typewriter from "./islands/typewriter.tsx";
import type {Manifest} from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/carousel.tsx": $carousel,
    "./islands/dashboard.tsx": $dashboard_1,
    "./islands/logout.tsx": $logout,
    "./islands/sidebar.tsx": $sidebar,
    "./islands/teamcards.tsx": $teamcards,
    "./islands/typewriter.tsx": $typewriter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
