mod app;

// Re-export organized component modules
pub mod components;

pub mod github;
pub mod utils;

// i18n module generated by leptos_i18n_build at compile time
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

// Re-export commonly used items
pub use app::*;
pub use components::*;
pub use github::*;
pub use i18n::*;
