name: Xodium CI/CD - Build

on:
  workflow_run:
    workflows: ["Xodium CI/CD - Quality Checks"]
    branches: [main, dev]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - id: setup-rust
        name: Setup Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - id: cache-rust
        name: Cache Rust
        uses: Swatinem/rust-cache@f51f967e158417aafa338a1e46ab22095f07aa01

      - id: cache-trunk
        name: Cache Trunk
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.cargo/bin/trunk
          key: ${{ runner.os }}-trunk-latest

      - id: cache-daisyui
        name: Cache DaisyUI
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: public/daisyui*.mjs
          key: ${{ runner.os }}-daisyui-${{ hashFiles('Trunk.toml') }}

      - id: setup-trunk
        name: Setup Trunk
        uses: jetli/trunk-action@1346cc09eace4beb84e403e199a471346d4684c9
        with:
          version: latest

      - id: build-app
        name: Build App
        env:
          DAISYUI_VERSION: "5.5.19"
        run: trunk build --release

      - id: deploy
        name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=xodiumorg --branch=${{ github.ref_name }} --commit-dirty=true
