name: Xodium CI/CD - Build App

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6

      - id: setup-rust
        name: Setup Rust
        uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7
        with:
          targets: wasm32-unknown-unknown

      - id: cache-rust
        name: Cache Rust
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5

      - id: setup-trunk
        name: Setup Trunk
        uses: jetli/trunk-action@1346cc09eace4beb84e403e199a471346d4684c9
        with:
          version: latest

      - id: build-app
        name: Build App
        run: trunk build --release

      - id: deploy
        name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=xodiumorg --branch=${{ github.ref_name }} --commit-dirty=true
