name: Xodium CI/CD - Build App

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: setup-rust
        name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - id: cache-rust
        name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - id: setup-trunk
        name: Setup Trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          version: latest

      - id: build-app
        name: Build App
        run: trunk build --release

      - id: deploy
        name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=xodiumorg --branch=${{ github.ref_name }}
