name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb
        with:
          deno-version: vx.x.x

      - name: Build step
        run: "deno task build"
        env:
          GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@7bded90d0d09cd99bbfb513966146315db97618b
        with:
          project: "xodium"
          entrypoint: "src/main.ts"
          root: "."
